services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: manra
      POSTGRES_PASSWORD: manra
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
