services:
  postgres:
    image: postgres:14
    container_name: weather_postgres
    environment:
      POSTGRES_USER: manra
      POSTGRES_PASSWORD: manra
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.11.0
    container_name: weather_airflow
    depends on:
      - postgres
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://manra:manra@postgres/weatherdb
    volumes:
      - ../dags:/opt/airflow/dags
      - ../etl:/opt/airflow/etl
    ports:
      - 8080:8080
    command: bash -c "airflow db init && airflow standalone"  

  etl:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: weather_etl
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=manra
      - POSTGRES_PASSWORD=manra
      - POSTGRES_DB=weatherdb
    volumes:
      - weather_data:/app/data
    command: ["python3.11", "etl/fetch_weather.py"]

volumes:
  postgres_data:
  weather_data:
    driver: local
